// This file will be auto-generated by: npm run db:generate
// For now, providing base types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          role: 'user' | 'admin'
          status: 'active' | 'suspended' | 'deleted'
          avatar_url: string | null
          preferences: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          role?: 'user' | 'admin'
          status?: 'active' | 'suspended' | 'deleted'
          avatar_url?: string | null
          preferences?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          role?: 'user' | 'admin'
          status?: 'active' | 'suspended' | 'deleted'
          avatar_url?: string | null
          preferences?: Json
          created_at?: string
          updated_at?: string
        }
      }
      learning_sessions: {
        Row: {
          id: string
          user_id: string
          workspace_type: string
          session_title: string | null
          input_content: string | null
          output_content: string | null
          mode: string | null
          language: string
          skill_level: string | null
          media_urls: string[] | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          workspace_type: string
          session_title?: string | null
          input_content?: string | null
          output_content?: string | null
          mode?: string | null
          language?: string
          skill_level?: string | null
          media_urls?: string[] | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          workspace_type?: string
          session_title?: string | null
          input_content?: string | null
          output_content?: string | null
          mode?: string | null
          language?: string
          skill_level?: string | null
          media_urls?: string[] | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      quiz_results: {
        Row: {
          id: string
          user_id: string
          quiz_title: string
          total_questions: number
          correct_answers: number
          score_percentage: number
          time_taken_seconds: number | null
          is_strict_mode: boolean
          questions_data: Json
          answers_data: Json
          proctoring_events: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          quiz_title: string
          total_questions: number
          correct_answers: number
          score_percentage: number
          time_taken_seconds?: number | null
          is_strict_mode?: boolean
          questions_data: Json
          answers_data: Json
          proctoring_events?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          quiz_title?: string
          total_questions?: number
          correct_answers?: number
          score_percentage?: number
          time_taken_seconds?: number | null
          is_strict_mode?: boolean
          questions_data?: Json
          answers_data?: Json
          proctoring_events?: Json | null
          created_at?: string
        }
      }
      study_sessions: {
        Row: {
          id: string
          user_id: string
          session_name: string
          timer_duration: number
          actual_duration: number | null
          topics: string[]
          notes: string | null
          status: string
          completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          session_name: string
          timer_duration: number
          actual_duration?: number | null
          topics: string[]
          notes?: string | null
          status?: string
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          session_name?: string
          timer_duration?: number
          actual_duration?: number | null
          topics?: string[]
          notes?: string | null
          status?: string
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      wellness_logs: {
        Row: {
          id: string
          user_id: string
          encrypted_content: string
          topic: string | null
          mood_rating: number | null
          crisis_detected: boolean
          disclaimer_acknowledged: boolean
          country_code: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          encrypted_content: string
          topic?: string | null
          mood_rating?: number | null
          crisis_detected?: boolean
          disclaimer_acknowledged?: boolean
          country_code?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          encrypted_content?: string
          topic?: string | null
          mood_rating?: number | null
          crisis_detected?: boolean
          disclaimer_acknowledged?: boolean
          country_code?: string
          created_at?: string
        }
      }
      cyber_safety_reports: {
        Row: {
          id: string
          user_id: string
          report_type: string
          input_data: Json
          analysis_result: Json
          risk_level: string
          recommendations: string[]
          media_analyzed: Json[]
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          report_type: string
          input_data: Json
          analysis_result: Json
          risk_level: string
          recommendations: string[]
          media_analyzed: Json[]
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          report_type?: string
          input_data?: Json
          analysis_result?: Json
          risk_level?: string
          recommendations?: string[]
          media_analyzed?: Json[]
          created_at?: string
        }
      }
      upload_metadata: {
        Row: {
          id: string
          user_id: string
          workspace_type: string
          file_name: string
          file_size: number
          file_type: string
          s3_key: string
          s3_url: string
          status: string
          upload_progress: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          workspace_type: string
          file_name: string
          file_size: number
          file_type: string
          s3_key: string
          s3_url: string
          status?: string
          upload_progress?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          workspace_type?: string
          file_name?: string
          file_size?: number
          file_type?: string
          s3_key?: string
          s3_url?: string
          status?: string
          upload_progress?: number
          created_at?: string
          updated_at?: string
        }
      }
      activity_logs: {
        Row: {
          id: string
          user_id: string
          action: string
          resource_type: string
          resource_id: string
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          action: string
          resource_type: string
          resource_id: string
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          action?: string
          resource_type?: string
          resource_id?: string
          metadata?: Json | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_role: 'user' | 'admin'
      account_status: 'active' | 'suspended' | 'deleted'
      workspace_type: 
        | 'general_chat'
        | 'explain_assist'
        | 'debug_workspace'
        | 'smart_summarizer'
        | 'quiz_arena'
        | 'interactive_quiz'
        | 'cyber_safety'
        | 'mental_wellness'
        | 'study_focus'
    }
  }
}
